#!/usr/bin/env php
<?php
//thank phpunit :) https://github.com/sebastianbergmann/phpunit/blob/master/phpunit
foreach ([__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php'] as $file) {
    if (file_exists($file)) {
        require_once $file;
        break;
    }
}

use FKSE\CsvToMarkdown\Command\ConvertCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new ConvertCommand());
$application->run();
